default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  host: postgresql
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
